// Code generated by SQLBoiler 4.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package repo

var TableNames = struct {
	Activity             string
	Author               string
	Book                 string
	BookAuthor           string
	BookCategory         string
	BookInitiater        string
	Category             string
	Line                 string
	LineRevision         string
	LineRevisionComment  string
	LineRevisionReaction string
	Page                 string
	PageRevision         string
	PageRevisionComment  string
	PageRevisionReaction string
	User                 string
}{
	Activity:             "activity",
	Author:               "author",
	Book:                 "book",
	BookAuthor:           "book_author",
	BookCategory:         "book_category",
	BookInitiater:        "book_initiater",
	Category:             "category",
	Line:                 "line",
	LineRevision:         "line_revision",
	LineRevisionComment:  "line_revision_comment",
	LineRevisionReaction: "line_revision_reaction",
	Page:                 "page",
	PageRevision:         "page_revision",
	PageRevisionComment:  "page_revision_comment",
	PageRevisionReaction: "page_revision_reaction",
	User:                 "user",
}
