// Code generated by SQLBoiler 4.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package repo

import (
	"strconv"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/strmangle"
)

// M type is for providing columns and column values to UpdateAll.
type M map[string]interface{}

// ErrSyncFail occurs during insert when the record could not be retrieved in
// order to populate default value information. This usually happens when LastInsertId
// fails or there was a primary key configuration that was not resolvable.
var ErrSyncFail = errors.New("repo: failed to synchronize data after insert")

type insertCache struct {
	query        string
	retQuery     string
	valueMapping []uint64
	retMapping   []uint64
}

type updateCache struct {
	query        string
	valueMapping []uint64
}

func makeCacheKey(cols boil.Columns, nzDefaults []string) string {
	buf := strmangle.GetBuffer()

	buf.WriteString(strconv.Itoa(cols.Kind))
	for _, w := range cols.Cols {
		buf.WriteString(w)
	}

	if len(nzDefaults) != 0 {
		buf.WriteByte('.')
	}
	for _, nz := range nzDefaults {
		buf.WriteString(nz)
	}

	str := buf.String()
	strmangle.PutBuffer(buf)
	return str
}

// Enum values for resource
const (
	ResourceBOOK     = "BOOK"
	ResourceLINE     = "LINE"
	ResourceUSER     = "USER"
	ResourceCATEGORY = "CATEGORY"
	ResourceAUTHOR   = "AUTHOR"
)

// Enum values for action
const (
	ActionCREATE = "CREATE"
	ActionUPDATE = "UPDATE"
	ActionDELETE = "DELETE"
)

// Enum values for revision_status
const (
	RevisionStatusINIT = "INIT"
	RevisionStatusREV1 = "REV1"
	RevisionStatusREV2 = "REV2"
	RevisionStatusDONE = "DONE"
)

// Enum values for user_role
const (
	UserRoleADMIN     = "ADMIN"
	UserRoleRAQIN     = "RAQIN"
	UserRoleVOLUNTEER = "VOLUNTEER"
)
