// Code generated by SQLBoiler 4.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package repo

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Activities", testActivitiesUpsert)

	t.Run("Authors", testAuthorsUpsert)

	t.Run("Books", testBooksUpsert)

	t.Run("BookAuthors", testBookAuthorsUpsert)

	t.Run("BookCategories", testBookCategoriesUpsert)

	t.Run("BookInitiaters", testBookInitiatersUpsert)

	t.Run("Categories", testCategoriesUpsert)

	t.Run("Lines", testLinesUpsert)

	t.Run("LineRevisions", testLineRevisionsUpsert)

	t.Run("LineRevisionComments", testLineRevisionCommentsUpsert)

	t.Run("LineRevisionReactions", testLineRevisionReactionsUpsert)

	t.Run("Pages", testPagesUpsert)

	t.Run("PageRevisions", testPageRevisionsUpsert)

	t.Run("PageRevisionComments", testPageRevisionCommentsUpsert)

	t.Run("PageRevisionReactions", testPageRevisionReactionsUpsert)

	t.Run("Users", testUsersUpsert)
}
