// Code generated by SQLBoiler 4.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package repo

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testPageRevisionReactions(t *testing.T) {
	t.Parallel()

	query := PageRevisionReactions()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testPageRevisionReactionsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PageRevisionReaction{}
	if err = randomize.Struct(seed, o, pageRevisionReactionDBTypes, true, pageRevisionReactionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PageRevisionReaction struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := PageRevisionReactions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testPageRevisionReactionsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PageRevisionReaction{}
	if err = randomize.Struct(seed, o, pageRevisionReactionDBTypes, true, pageRevisionReactionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PageRevisionReaction struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := PageRevisionReactions().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := PageRevisionReactions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testPageRevisionReactionsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PageRevisionReaction{}
	if err = randomize.Struct(seed, o, pageRevisionReactionDBTypes, true, pageRevisionReactionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PageRevisionReaction struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := PageRevisionReactionSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := PageRevisionReactions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testPageRevisionReactionsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PageRevisionReaction{}
	if err = randomize.Struct(seed, o, pageRevisionReactionDBTypes, true, pageRevisionReactionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PageRevisionReaction struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := PageRevisionReactionExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if PageRevisionReaction exists: %s", err)
	}
	if !e {
		t.Errorf("Expected PageRevisionReactionExists to return true, but got false.")
	}
}

func testPageRevisionReactionsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PageRevisionReaction{}
	if err = randomize.Struct(seed, o, pageRevisionReactionDBTypes, true, pageRevisionReactionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PageRevisionReaction struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	pageRevisionReactionFound, err := FindPageRevisionReaction(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if pageRevisionReactionFound == nil {
		t.Error("want a record, got nil")
	}
}

func testPageRevisionReactionsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PageRevisionReaction{}
	if err = randomize.Struct(seed, o, pageRevisionReactionDBTypes, true, pageRevisionReactionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PageRevisionReaction struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = PageRevisionReactions().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testPageRevisionReactionsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PageRevisionReaction{}
	if err = randomize.Struct(seed, o, pageRevisionReactionDBTypes, true, pageRevisionReactionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PageRevisionReaction struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := PageRevisionReactions().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testPageRevisionReactionsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	pageRevisionReactionOne := &PageRevisionReaction{}
	pageRevisionReactionTwo := &PageRevisionReaction{}
	if err = randomize.Struct(seed, pageRevisionReactionOne, pageRevisionReactionDBTypes, false, pageRevisionReactionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PageRevisionReaction struct: %s", err)
	}
	if err = randomize.Struct(seed, pageRevisionReactionTwo, pageRevisionReactionDBTypes, false, pageRevisionReactionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PageRevisionReaction struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = pageRevisionReactionOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = pageRevisionReactionTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := PageRevisionReactions().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testPageRevisionReactionsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	pageRevisionReactionOne := &PageRevisionReaction{}
	pageRevisionReactionTwo := &PageRevisionReaction{}
	if err = randomize.Struct(seed, pageRevisionReactionOne, pageRevisionReactionDBTypes, false, pageRevisionReactionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PageRevisionReaction struct: %s", err)
	}
	if err = randomize.Struct(seed, pageRevisionReactionTwo, pageRevisionReactionDBTypes, false, pageRevisionReactionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PageRevisionReaction struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = pageRevisionReactionOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = pageRevisionReactionTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := PageRevisionReactions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func pageRevisionReactionBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *PageRevisionReaction) error {
	*o = PageRevisionReaction{}
	return nil
}

func pageRevisionReactionAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *PageRevisionReaction) error {
	*o = PageRevisionReaction{}
	return nil
}

func pageRevisionReactionAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *PageRevisionReaction) error {
	*o = PageRevisionReaction{}
	return nil
}

func pageRevisionReactionBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *PageRevisionReaction) error {
	*o = PageRevisionReaction{}
	return nil
}

func pageRevisionReactionAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *PageRevisionReaction) error {
	*o = PageRevisionReaction{}
	return nil
}

func pageRevisionReactionBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *PageRevisionReaction) error {
	*o = PageRevisionReaction{}
	return nil
}

func pageRevisionReactionAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *PageRevisionReaction) error {
	*o = PageRevisionReaction{}
	return nil
}

func pageRevisionReactionBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *PageRevisionReaction) error {
	*o = PageRevisionReaction{}
	return nil
}

func pageRevisionReactionAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *PageRevisionReaction) error {
	*o = PageRevisionReaction{}
	return nil
}

func testPageRevisionReactionsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &PageRevisionReaction{}
	o := &PageRevisionReaction{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, pageRevisionReactionDBTypes, false); err != nil {
		t.Errorf("Unable to randomize PageRevisionReaction object: %s", err)
	}

	AddPageRevisionReactionHook(boil.BeforeInsertHook, pageRevisionReactionBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	pageRevisionReactionBeforeInsertHooks = []PageRevisionReactionHook{}

	AddPageRevisionReactionHook(boil.AfterInsertHook, pageRevisionReactionAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	pageRevisionReactionAfterInsertHooks = []PageRevisionReactionHook{}

	AddPageRevisionReactionHook(boil.AfterSelectHook, pageRevisionReactionAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	pageRevisionReactionAfterSelectHooks = []PageRevisionReactionHook{}

	AddPageRevisionReactionHook(boil.BeforeUpdateHook, pageRevisionReactionBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	pageRevisionReactionBeforeUpdateHooks = []PageRevisionReactionHook{}

	AddPageRevisionReactionHook(boil.AfterUpdateHook, pageRevisionReactionAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	pageRevisionReactionAfterUpdateHooks = []PageRevisionReactionHook{}

	AddPageRevisionReactionHook(boil.BeforeDeleteHook, pageRevisionReactionBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	pageRevisionReactionBeforeDeleteHooks = []PageRevisionReactionHook{}

	AddPageRevisionReactionHook(boil.AfterDeleteHook, pageRevisionReactionAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	pageRevisionReactionAfterDeleteHooks = []PageRevisionReactionHook{}

	AddPageRevisionReactionHook(boil.BeforeUpsertHook, pageRevisionReactionBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	pageRevisionReactionBeforeUpsertHooks = []PageRevisionReactionHook{}

	AddPageRevisionReactionHook(boil.AfterUpsertHook, pageRevisionReactionAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	pageRevisionReactionAfterUpsertHooks = []PageRevisionReactionHook{}
}

func testPageRevisionReactionsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PageRevisionReaction{}
	if err = randomize.Struct(seed, o, pageRevisionReactionDBTypes, true, pageRevisionReactionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PageRevisionReaction struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := PageRevisionReactions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testPageRevisionReactionsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PageRevisionReaction{}
	if err = randomize.Struct(seed, o, pageRevisionReactionDBTypes, true); err != nil {
		t.Errorf("Unable to randomize PageRevisionReaction struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(pageRevisionReactionColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := PageRevisionReactions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testPageRevisionReactionToOnePageRevisionUsingPageRevision(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local PageRevisionReaction
	var foreign PageRevision

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, pageRevisionReactionDBTypes, false, pageRevisionReactionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PageRevisionReaction struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, pageRevisionDBTypes, false, pageRevisionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PageRevision struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.PageRevisionID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.PageRevision().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := PageRevisionReactionSlice{&local}
	if err = local.L.LoadPageRevision(ctx, tx, false, (*[]*PageRevisionReaction)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.PageRevision == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.PageRevision = nil
	if err = local.L.LoadPageRevision(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.PageRevision == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testPageRevisionReactionToOneUserUsingReactor(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local PageRevisionReaction
	var foreign User

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, pageRevisionReactionDBTypes, false, pageRevisionReactionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PageRevisionReaction struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, userDBTypes, false, userColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize User struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.ReactorID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Reactor().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := PageRevisionReactionSlice{&local}
	if err = local.L.LoadReactor(ctx, tx, false, (*[]*PageRevisionReaction)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Reactor == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Reactor = nil
	if err = local.L.LoadReactor(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Reactor == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testPageRevisionReactionToOneSetOpPageRevisionUsingPageRevision(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a PageRevisionReaction
	var b, c PageRevision

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, pageRevisionReactionDBTypes, false, strmangle.SetComplement(pageRevisionReactionPrimaryKeyColumns, pageRevisionReactionColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, pageRevisionDBTypes, false, strmangle.SetComplement(pageRevisionPrimaryKeyColumns, pageRevisionColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, pageRevisionDBTypes, false, strmangle.SetComplement(pageRevisionPrimaryKeyColumns, pageRevisionColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*PageRevision{&b, &c} {
		err = a.SetPageRevision(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.PageRevision != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.PageRevisionReactions[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.PageRevisionID != x.ID {
			t.Error("foreign key was wrong value", a.PageRevisionID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.PageRevisionID))
		reflect.Indirect(reflect.ValueOf(&a.PageRevisionID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.PageRevisionID != x.ID {
			t.Error("foreign key was wrong value", a.PageRevisionID, x.ID)
		}
	}
}
func testPageRevisionReactionToOneSetOpUserUsingReactor(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a PageRevisionReaction
	var b, c User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, pageRevisionReactionDBTypes, false, strmangle.SetComplement(pageRevisionReactionPrimaryKeyColumns, pageRevisionReactionColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*User{&b, &c} {
		err = a.SetReactor(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Reactor != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.ReactorPageRevisionReactions[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.ReactorID != x.ID {
			t.Error("foreign key was wrong value", a.ReactorID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.ReactorID))
		reflect.Indirect(reflect.ValueOf(&a.ReactorID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.ReactorID != x.ID {
			t.Error("foreign key was wrong value", a.ReactorID, x.ID)
		}
	}
}

func testPageRevisionReactionsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PageRevisionReaction{}
	if err = randomize.Struct(seed, o, pageRevisionReactionDBTypes, true, pageRevisionReactionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PageRevisionReaction struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testPageRevisionReactionsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PageRevisionReaction{}
	if err = randomize.Struct(seed, o, pageRevisionReactionDBTypes, true, pageRevisionReactionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PageRevisionReaction struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := PageRevisionReactionSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testPageRevisionReactionsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PageRevisionReaction{}
	if err = randomize.Struct(seed, o, pageRevisionReactionDBTypes, true, pageRevisionReactionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PageRevisionReaction struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := PageRevisionReactions().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	pageRevisionReactionDBTypes = map[string]string{`ID`: `int`, `PageRevisionID`: `int`, `ReactorID`: `int`, `Reaction`: `enum('NONE','APPROVE','DISAPPROVE')`, `CreatedAt`: `timestamp`, `UpdatedAt`: `timestamp`, `DeletedAt`: `timestamp`}
	_                           = bytes.MinRead
)

func testPageRevisionReactionsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(pageRevisionReactionPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(pageRevisionReactionAllColumns) == len(pageRevisionReactionPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &PageRevisionReaction{}
	if err = randomize.Struct(seed, o, pageRevisionReactionDBTypes, true, pageRevisionReactionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PageRevisionReaction struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := PageRevisionReactions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, pageRevisionReactionDBTypes, true, pageRevisionReactionPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize PageRevisionReaction struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testPageRevisionReactionsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(pageRevisionReactionAllColumns) == len(pageRevisionReactionPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &PageRevisionReaction{}
	if err = randomize.Struct(seed, o, pageRevisionReactionDBTypes, true, pageRevisionReactionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PageRevisionReaction struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := PageRevisionReactions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, pageRevisionReactionDBTypes, true, pageRevisionReactionPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize PageRevisionReaction struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(pageRevisionReactionAllColumns, pageRevisionReactionPrimaryKeyColumns) {
		fields = pageRevisionReactionAllColumns
	} else {
		fields = strmangle.SetComplement(
			pageRevisionReactionAllColumns,
			pageRevisionReactionPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := PageRevisionReactionSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testPageRevisionReactionsUpsert(t *testing.T) {
	t.Parallel()

	if len(pageRevisionReactionAllColumns) == len(pageRevisionReactionPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}
	if len(mySQLPageRevisionReactionUniqueColumns) == 0 {
		t.Skip("Skipping table with no unique columns to conflict on")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := PageRevisionReaction{}
	if err = randomize.Struct(seed, &o, pageRevisionReactionDBTypes, false); err != nil {
		t.Errorf("Unable to randomize PageRevisionReaction struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert PageRevisionReaction: %s", err)
	}

	count, err := PageRevisionReactions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, pageRevisionReactionDBTypes, false, pageRevisionReactionPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize PageRevisionReaction struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert PageRevisionReaction: %s", err)
	}

	count, err = PageRevisionReactions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
